version: '3.4'

services:
  graphqlbackend:
    container_name: graphql-backend
    image: ${DOCKER_REGISTRY-}graphqlbackend
    build:
      context: .
      dockerfile: graphqlbackend/Dockerfile
    ports: 
      - "8080:8080"
    networks: 
      - gql-network

  mongoDB:
    container_name: mongodb
    image: mongo:latest
    command: mongod --quiet --logpath /dev/null
    ports:
      - 27017:27017
    networks:
      - gql-network

networks:
  gql-network:
    driver: bridge
